SELECT
    sum (case when [patient_patientid] is null then 0 else 1 end) as "patient_patientid_NONNULLCOUNT",
    sum (case when [patient_patientid] is null then 1 else 0 end) as "patient_patientid_NULLCOUNT",
    sum (case when [patient_typ] is null then 0 else 1 end) as "patient_typ_NONNULLCOUNT",
    sum (case when [patient_typ] is null then 1 else 0 end) as "patient_typ_NULLCOUNT",
    sum (case when [patient_status] is null then 0 else 1 end) as "patient_status_NONNULLCOUNT",
    sum (case when [patient_status] is null then 1 else 0 end) as "patient_status_NULLCOUNT",
    sum (case when [fall_nummer] is null then 0 else 1 end) as "fall_nummer_NONNULLCOUNT",
    sum (case when [fall_nummer] is null then 1 else 0 end) as "fall_nummer_NULLCOUNT",
    sum (case when [fall_typ] is null then 0 else 1 end) as "fall_typ_NONNULLCOUNT",
    sum (case when [fall_typ] is null then 1 else 0 end) as "fall_typ_NULLCOUNT",
    sum (case when [fall_status] is null then 0 else 1 end) as "fall_status_NONNULLCOUNT",
    sum (case when [fall_status] is null then 1 else 0 end) as "fall_status_NULLCOUNT",
    sum (case when [datum_betreuung] is null then 0 else 1 end) as "datum_betreuung_NONNULLCOUNT",
    sum (case when [datum_betreuung] is null then 1 else 0 end) as "datum_betreuung_NULLCOUNT",
    sum (case when [dauer_betreuung_in_min] is null then 0 else 1 end) as "dauer_betreuung_in_min_NONNULLCOUNT",
    sum (case when [dauer_betreuung_in_min] is null then 1 else 0 end) as "dauer_betreuung_in_min_NULLCOUNT",
    sum (case when [mitarbeiter_personalnummer] is null then 0 else 1 end) as "mitarbeiter_personalnummer_NONNULLCOUNT",
    sum (case when [mitarbeiter_personalnummer] is null then 1 else 0 end) as "mitarbeiter_personalnummer_NULLCOUNT",
    sum (case when [mitarbeiter_anstellungsnummer] is null then 0 else 1 end) as "mitarbeiter_anstellungsnummer_NONNULLCOUNT",
    sum (case when [mitarbeiter_anstellungsnummer] is null then 1 else 0 end) as "mitarbeiter_anstellungsnummer_NULLCOUNT",
    sum (case when [mitarbeiter_login] is null then 0 else 1 end) as "mitarbeiter_login_NONNULLCOUNT",
    sum (case when [mitarbeiter_login] is null then 1 else 0 end) as "mitarbeiter_login_NULLCOUNT",
    sum (case when [BATCH_RUN_ID] is null then 0 else 1 end) as "BATCH_RUN_ID_NONNULLCOUNT",
    sum (case when [BATCH_RUN_ID] is null then 1 else 0 end) as "BATCH_RUN_ID_NULLCOUNT"
FROM [Atelier_DataScience].[atl].[TACS_DATEN]