SELECT
    sum (case when [PATIENTID] is null then 0 else 1 end) as "PATIENTID_NONNULLCOUNT",
    sum (case when [PATIENTID] is null then 1 else 0 end) as "PATIENTID_NULLCOUNT",
    sum (case when [CASEID] is null then 0 else 1 end) as "CASEID_NONNULLCOUNT",
    sum (case when [CASEID] is null then 1 else 0 end) as "CASEID_NULLCOUNT",
    sum (case when [CASETYP] is null then 0 else 1 end) as "CASETYP_NONNULLCOUNT",
    sum (case when [CASETYP] is null then 1 else 0 end) as "CASETYP_NULLCOUNT",
    sum (case when [CASESTATUS] is null then 0 else 1 end) as "CASESTATUS_NONNULLCOUNT",
    sum (case when [CASESTATUS] is null then 1 else 0 end) as "CASESTATUS_NULLCOUNT",
    sum (case when [FALAR] is null then 0 else 1 end) as "FALAR_NONNULLCOUNT",
    sum (case when [FALAR] is null then 1 else 0 end) as "FALAR_NULLCOUNT",
    sum (case when [BEGDT] is null then 0 else 1 end) as "BEGDT_NONNULLCOUNT",
    sum (case when [BEGDT] is null then 1 else 0 end) as "BEGDT_NULLCOUNT",
    sum (case when [ENDDT] is null then 0 else 1 end) as "ENDDT_NONNULLCOUNT",
    sum (case when [ENDDT] is null then 1 else 0 end) as "ENDDT_NULLCOUNT",
    sum (case when [PATIENTTYP] is null then 0 else 1 end) as "PATIENTTYP_NONNULLCOUNT",
    sum (case when [PATIENTTYP] is null then 1 else 0 end) as "PATIENTTYP_NULLCOUNT",
    sum (case when [PATIENTSTATUS] is null then 0 else 1 end) as "PATIENTSTATUS_NONNULLCOUNT",
    sum (case when [PATIENTSTATUS] is null then 1 else 0 end) as "PATIENTSTATUS_NULLCOUNT"
FROM [Atelier_DataScience].[atl].[V_LA_ISH_NFAL_NORM]