from src.features.model.appointment import Appointment
from src.features.model.bed import Bed
from src.features.model.employee import Employee
from src.features.model.treatment import Treatment
from src.features.model.case import Case
from src.features.model.chop import Chop
from src.features.model.device import Device
from src.features.model.icdcode import ICDCode
from src.features.model.medication import Medication
from src.features.model.room import Room
from src.features.model.ward import Ward
from src.features.model.stay import Stay
from src.features.model.partner import Partner
from src.features.model.patient import Patient
from src.features.model.risk import Risk
from src.features.model.surgery import Surgery
from src.features.model.building import Building
