SELECT	CHOPCODE
		,CHOPVERWENDUNGSJAHR
		,CHOP
		,CHOPCODELEVEL1
		,CHOPLEVEL1
		,CHOPCODELEVEL2
		,CHOPLEVEL2
		,CHOPCODELEVEL3
		,CHOPLEVEL3
		,CHOPCODELEVEL4
		,CHOPLEVEL4
		,CHOPCODELEVEL5
		,CHOPLEVEL5
		,CHOPCODELEVEL6
		,CHOPLEVEL6
		,CHOPSTATUS
		,CHOPSAPKATALOGID
FROM [Atelier_DataScience].[atl].[V_DH_REF_CHOP]
