SELECT 
    [PATIENTID]
    ,[CASEID]
    ,[DRUG_TEXT]
    ,[DRUG_ATC]
    ,[DRUG_QUANTITY]
    ,[DRUG_UNIT]
    ,[DRUG_DISPFORM]
    ,[DRUG_SUBMISSION]
FROM [Atelier_DataScience].[atl].[V_LA_IPD_DRUG_NORM]
