SELECT 
    [PATIENTID]
    ,[CASEID]
    ,[CASETYP]
    ,[CASESTATUS]
    ,[FALAR]
    ,[BEGDT]
    ,[ENDDT]
    ,[PATIENTTYP]
    ,[PATIENTSTATUS]
FROM [Atelier_DataScience].[atl].[V_LA_ISH_NFAL_NORM]
