SELECT * FROM [Atelier_DataScience].[atl].[V_DH_DIM_MITARBEITER_CUR] WHERE MITARBEITERID in
(SELECT distinct MITARBEITERID from [Atelier_DataScience].[atl].[V_DH_FACT_TERMINMITARBEITER] WHERE TERMINID in
	(SELECT TERMINID FROM [Atelier_DataScience].[atl].[V_DH_FACT_TERMINGERAET]
	WHERE GERAETID IN
		(SELECT GERAETID
		  FROM [Atelier_DataScience].[atl].[V_DH_DIM_GERAET_CUR]
		  WHERE GERAETNAME ='ECC')
	AND TERMINSTART_TS > '2018-01-01')
)


SELECT * FROM [Atelier_DataScience].[atl].[V_DH_DIM_RAUM_CUR] WHERE RAUMID in
(SELECT distinct RAUMID from [Atelier_DataScience].[atl].[V_DH_FACT_TERMINRAUM] WHERE TERMINID in
	(SELECT TERMINID FROM [Atelier_DataScience].[atl].[V_DH_FACT_TERMINGERAET]
	WHERE GERAETID IN
		(SELECT GERAETID
		  FROM [Atelier_DataScience].[atl].[V_DH_DIM_GERAET_CUR]
		  WHERE GERAETNAME ='ECC')
	AND TERMINSTART_TS > '2018-01-01')
)